export interface NotificationBannerDTO {
  id: string;
  title: string;
  message_en: string;
  message_sv: string;
  linkUrl: string | null;
  linkText_en: string | null;
  linkText_sv: string | null;
  couponCode: string | null;
  showPhone: boolean;
  showEmail: boolean;
  backgroundColor: string;
  textColor: string;
  backgroundType: 'solid' | 'gradient';
  gradientEndColor: string | null;
  gradientDirection: string | null;
  fontWeight: 'normal' | 'medium' | 'semibold' | 'bold';
  fontSize: 'xs' | 'sm' | 'base' | 'lg';
  icon: string | null;
  isActive: boolean;
  showOnAuthPages: boolean;
  showOnAdminPanel: boolean;
  isDismissible: boolean;
  startDate: Date | null;
  endDate: Date | null;
  showOnPages: string[];
  priority: number;
  impressions: number;
  clicks: number;
  dismissals: number;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface CreateNotificationBannerDTO {
  title: string;
  message_en: string;
  message_sv: string;
  linkUrl?: string | null;
  linkText_en?: string | null;
  linkText_sv?: string | null;
  couponCode?: string | null;
  showPhone?: boolean;
  showEmail?: boolean;
  backgroundColor?: string;
  textColor?: string;
  backgroundType?: 'solid' | 'gradient';
  gradientEndColor?: string | null;
  gradientDirection?: string | null;
  fontWeight?: 'normal' | 'medium' | 'semibold' | 'bold';
  fontSize?: 'xs' | 'sm' | 'base' | 'lg';
  icon?: string | null;
  isActive?: boolean;
  showOnAuthPages?: boolean;
  showOnAdminPanel?: boolean;
  isDismissible?: boolean;
  startDate?: Date | null;
  endDate?: Date | null;
  showOnPages?: string[];
  priority?: number;
}

export interface UpdateNotificationBannerDTO {
  title?: string;
  message_en?: string;
  message_sv?: string;
  linkUrl?: string | null;
  linkText_en?: string | null;
  linkText_sv?: string | null;
  couponCode?: string | null;
  showPhone?: boolean;
  showEmail?: boolean;
  backgroundColor?: string;
  textColor?: string;
  backgroundType?: 'solid' | 'gradient';
  gradientEndColor?: string | null;
  gradientDirection?: string | null;
  fontWeight?: 'normal' | 'medium' | 'semibold' | 'bold';
  fontSize?: 'xs' | 'sm' | 'base' | 'lg';
  icon?: string | null;
  isActive?: boolean;
  showOnAuthPages?: boolean;
  showOnAdminPanel?: boolean;
  isDismissible?: boolean;
  startDate?: Date | null;
  endDate?: Date | null;
  showOnPages?: string[];
  priority?: number;
}

export interface ActiveNotificationBannerDTO {
  id: string;
  title: string;
  message_en: string;
  message_sv: string;
  linkUrl: string | null;
  linkText_en: string | null;
  linkText_sv: string | null;
  couponCode: string | null;
  showPhone: boolean;
  showEmail: boolean;
  contactPhone: string | null;
  contactEmail: string | null;
  backgroundColor: string;
  textColor: string;
  backgroundType: 'solid' | 'gradient';
  gradientEndColor: string | null;
  gradientDirection: string | null;
  fontWeight: 'normal' | 'medium' | 'semibold' | 'bold';
  fontSize: 'xs' | 'sm' | 'base' | 'lg';
  icon: string | null;
  isActive: boolean;
  showOnAuthPages: boolean;
  showOnAdminPanel: boolean;
  isDismissible: boolean;
  startDate: Date | null;
  endDate: Date | null;
  showOnPages: string[];
  priority: number;
}
